name = "qim-quran"
main = ".open-next/worker.js"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "qim-quran"

[vars]
# Add any environment variables here if needed
